name: Product Release Notes
description: Generate release notes filtered by product label

inputs:
  product-label:
    description: "The product label to filter PRs by (e.g. product:cli)"
    required: true
  tag:
    description: "The current release tag"
    required: true
  previous-tag:
    description: "The previous release tag (empty for first release)"
    required: false
    default: ""

outputs:
  notes:
    description: "The generated release notes markdown"
    value: ${{ steps.generate.outputs.notes }}

runs:
  using: composite
  steps:
    - name: Generate filtered release notes
      id: generate
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        PRODUCT_LABEL: ${{ inputs.product-label }}
        TAG: ${{ inputs.tag }}
        PREV_TAG: ${{ inputs.previous-tag }}
      run: |
        set -euo pipefail

        # Determine date range from tags for bulk PR query
        TAG_DATE=$(git log -1 --format="%aI" "$TAG")

        if [ -n "$PREV_TAG" ]; then
          PREV_DATE=$(git log -1 --format="%aI" "$PREV_TAG")
          SEARCH_QUERY="merged:${PREV_DATE}..${TAG_DATE}"
          FULL_CHANGELOG_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/compare/${PREV_TAG}...${TAG}"
        else
          SEARCH_QUERY="merged:<=${TAG_DATE}"
          FULL_CHANGELOG_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commits/${TAG}"
        fi

        # Bulk query: fetch all merged PRs with the product label in one call
        NOTES=""
        PR_LIST=$(gh pr list \
          --state merged \
          --label "$PRODUCT_LABEL" \
          --search "$SEARCH_QUERY" \
          --json number,title,author \
          --limit 200 \
          --jq '.[] | "* \(.title) by @\(.author.login) in #\(.number)"')

        if [ -n "$PR_LIST" ]; then
          NOTES="## What's Changed"$'\n'"${PR_LIST}"$'\n'
        else
          NOTES="No product-specific changes in this release."
        fi

        FINAL="${NOTES}"$'\n'"**Full Changelog**: ${FULL_CHANGELOG_URL}"

        # Write multiline output with unique delimiter
        DELIM="RELEASE_NOTES_EOF_${RANDOM}_$$"
        {
          echo "notes<<${DELIM}"
          echo "$FINAL"
          echo "${DELIM}"
        } >> "$GITHUB_OUTPUT"
